# Generated by Django 4.0.1 on 2022-05-17 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Research', '0004_remove_experiment_dataset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('types_selected', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=100)),
                ('algorithm_group', models.CharField(max_length=100)),
                ('algorithm_specific', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('duration', models.TimeField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('result', models.ImageField(upload_to='static/images/experiments/')),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Research.datasetconfiguration')),
            ],
        ),
    ]
